In [ ]:
## Numpy kütüphanesi
Doğrusal cebir, vektör uzayları ve vektör uzayları arasındaki doğrusal dönüşümler hakkında bilgiler içeren bir matematik dalıdır.
# Makine öğrenmesinde kullanulan algoritmalar ağırlıklı olarak doğrusal cebire dayanır. Bu nedenle, vektörlerin ve matrislerin ne olduğunu,
## onlarla hangi işlemlerin yapılabileceğini bilmek önemlidir.
# Vektör, bir büyüklük ve bir yön ile tanımlanabilen bir niteliktir.

In [1]:
import numpy as np 

In [3]:
np.array(([2,3,4,5]))

array([2, 3, 4, 5])

In [4]:
np.array(([1,2,3,4],[1,2,3,2]))

array([[1, 2, 3, 4],
       [1, 2, 3, 2]])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.full((2,2),"0")

array([['0', '0'],
       ['0', '0']], dtype='<U1')

In [10]:
np.arange(1,15,2) ##1 ile 15 arasında ikişer ikişer artarak bir matris oluşturur

array([ 1,  3,  5,  7,  9, 11, 13])

In [17]:
np.linspace(0.0,10.0,num=5)  #num kaça bölüneecğini gösterir.


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.random.rand(2,2) ## rastgele sayılardan oluşan  float türünde matris oluşturur.


array([[0.16515993, 0.37795334],
       [0.92180066, 0.82433031]])

In [21]:
np.random.randint(1,4,size=(2,2))

array([[2, 2],
       [3, 3]])

In [22]:
dizi=np.arange(16)
dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
dizi.shape=(4,4)
dizi



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
dizi.ndim

2

In [37]:
x=dizi.ravel() ## çok boyutlu diziyi tek boyutlu diziye çevirir.
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
dizi2=np.array(([2,4,6],[8,10,12]))
dizi2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [47]:
dizi2.min()
dizi2.max()
dizi2.sum()
dizi2.prod() ## çarpımları verir.
dizi2.std()##standart sapmayı verir
dizi2.var() ## varyansı verir


11.666666666666666

In [51]:
y=np.arange(16)
y


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
y[4] ## 4.indisteki elemanı verir.

4

In [54]:
y[1:5]

array([1, 2, 3, 4])

In [58]:
y[:-1] ## son elemana kadar alır son elemanı almaz. -1 son elemanın alınmayacağını gösterir.


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
y[1::2] ## 1.indisten  başlayarak ikişer ikişer atlayarak elemanları gösterir

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [61]:
z=np.random.randint(0,16,(4,4))
z

array([[ 6,  3,  8,  2],
       [ 0, 13, 13,  5],
       [14,  4,  3,  0],
       [13, 10, 10,  7]])

In [62]:
z[2,3]  ## 2.satır 3.sutundaki elemanı verir

0

In [64]:
z[0,:]

array([6, 3, 8, 2])